#!/usr/bin/env python3
"""Generate src/data/mapOpportunities.ts (PUBLIC, PII-scrubbed) from pipeline output.
Run after hvac_engine.py:  python pipeline/gen_map_data.py"""
import csv, json, os
HERE = os.path.dirname(os.path.abspath(__file__))
B = os.path.join(HERE, "building_opportunities.csv")
Q = os.path.join(HERE, "qualified_opportunities.csv")
OUT = os.path.join(HERE, "..", "src", "data", "mapOpportunities.ts")

bo = {r["address"]: r for r in csv.DictReader(open(B))}
qo = {r["address"]: r for r in csv.DictReader(open(Q))} if os.path.exists(Q) else {}
pts = []
for addr, r in bo.items():
    if not (r.get("lat") and r.get("long")):
        continue
    try:
        sc = int(r["score"])
    except ValueError:
        continue
    if sc < 45:
        continue
    q = qo.get(addr)
    pts.append({
        "address": addr, "lat": float(r["lat"]), "lng": float(r["long"]), "score": sc,
        "segment": r["segment"], "signals": r.get("signals", ""), "systemAge": str(r.get("system_age", "")),
        "acute": int(r.get("acute_count") or 0), "open": str(r.get("acute_open", "")).lower() == "true",
        "qualified": bool(q and (q.get("email") or q.get("phone"))),
        "confidence": (q or {}).get("confidence", ""),   # label only, no raw PII
        "why": (q or {}).get("why", ""),                  # rationale never contains the raw email/phone
    })
pts.sort(key=lambda p: (-p["qualified"], -p["score"]))
pts = pts[:400]
ts = ("// AUTO-GENERATED by pipeline/gen_map_data.py — do not edit by hand.\n"
      "// Live SF opportunities (DataSF 311 + permits -> scored). Contact PII is\n"
      "// intentionally withheld from this public repo; fields below are public-record derived.\n\n"
      "export type MapOpportunity = {\n"
      "  address: string; lat: number; lng: number; score: number; segment: string;\n"
      "  signals: string; systemAge: string; acute: number; open: boolean;\n"
      "  qualified: boolean; confidence: string; why: string;\n};\n\n"
      "export const mapOpportunities: MapOpportunity[] = " + json.dumps(pts, indent=2) + ";\n")
open(OUT, "w").write(ts)
print(f"wrote {OUT}: {len(pts)} points ({sum(1 for p in pts if p['qualified'])} enriched)")
